MoveNames:: ; b0000 (2c:4000)
	db "POUND@"
	db "$מכת קרטה@"
	db "$סטירה כפולה@"
	db "$אגרוף שביט@"
	db "$מגה אגרוף@"
	db "$יום הפרעון@"
	db "$אגרוף אש@"
	db "$אגרוף קרח@"
	db "$אגרוף רעם@"
	db "$שריטה@"
	db "VICEGRIP@"
	db "$גיליוטינה@"
	db "$רוח תער@"
	db "$ריקוד חרבות@"
	db "$חיתוך@"
	db "$משב רוח@"
	db "$מתקפת כנף@"
	db "$מערבולת@"
	db "$תעופה@"
	db "$קשירה@"
	db "SLAM@"
	db "$הצלפת גפן@"
	db "$רקיעה@"
	db "$בעיטה כפולה@"
	db "$מגה בעיטה@"
	db "JUMP KICK@"
	db "ROLLING KICK@"
	db "$מתקפת חול@"
	db "$נגיחה@"
	db "HORN ATTACK@"
	db "$מתקפת זעם@"
	db "HORN DRILL@"
	db "$בלימה@"
	db "BODY SLAM@"
	db "WRAP@"
	db "TAKE DOWN@"
	db "THRASH@"
	db "DOUBLE-EDGE@"
	db "$הצלפת זנב@"
	db "$עקיצת רעל@"
	db "TWINEEDLE@"
	db "PIN MISSILE@"
	db "LEER@"
	db "$נשיכה@"
	db "$נהמה@"
	db "$שאגה@"
	db "$שירה@"
	db "$מתקפה על קולית@"
	db "$פיצוץ על קולי@"
	db "$נטרול@"
	db "$חומצה@"
	db "$גחלת@"
	db "$להביור@"
	db "$ערפל@"
	db "$תותח מים@"
	db "HYDRO PUMP@"
	db "$גלישה@"
	db "$קרן קרח@"
	db "BLIZZARD@"
	db "$קרן על חושית@"
	db "$קרן בועות@"
	db "AURORA BEAM@"
	db "HYPER BEAM@"
	db "$ניקור@"
	db "DRILL PECK@"
	db "SUBMISSION@"
	db "LOW KICK@"
	db "COUNTER@"
	db "$זריקה@"
	db "STRENGTH@"
	db "$ספיגה@"
	db "MEGA DRAIN@"
	db "LEECH SEED@"
	db "$גדילה@"
	db "$עלי תער@"
	db "$קרן סולארית@"
	db "$אבקת רעל@"
	db "STUN SPORE@"
	db "$אבקת שינה@"
	db "$ריקוד עלי כותרת@"
	db "$יריית חוט@"
	db "$זעם דרקון@"
	db "$סיבוב אש@"
	db "$הלם רעם@"
	db "$מכת ברק@"
	db "$גל רעם@"
	db "$רעם@"
	db "$זריקת סלעים@"
	db "$רעידת אדמה@"
	db "FISSURE@"
	db "$חפירה@"
	db "TOXIC@"
	db "$בלבול@"
	db "$על חושי@"
	db "$היפנוזה@"
	db "$מדיטציה@"
	db "$זריזות@"
	db "$מתקפה מהירה@"
	db "$זעם@"
	db "$שיגור@"
	db "NIGHT SHADE@"
	db "MIMIC@"
	db "SCREECH@"
	db "$צוות כפול@"
	db "RECOVER@"
	db "$התקשחות@"
	db "$מזעור@"
	db "$מסך עשן@"
	db "$קרן בלבול@"
	db "WITHDRAW@"
	db "DEFENSE CURL@"
	db "$מחסום@"
	db "LIGHT SCREEN@"
	db "HAZE@"
	db "$השתקפות@"
	db "FOCUS ENERGY@"
	db "BIDE@"
	db "$מטרונום@"
	db "$מהלך מראה@"
	db "SELFDESTRUCT@"
	db "EGG BOMB@"
	db "$ליקוק@"
	db "SMOG@"
	db "SLUDGE@"
	db "BONE CLUB@"
	db "$פיצוץ אש@"
	db "$מפל מים@"
	db "CLAMP@"
	db "$מהירות@"
	db "SKULL BASH@"
	db "$תותח סיכות@"
	db "CONSTRICT@"
	db "$שכחה@"
	db "KINESIS@"
	db "SOFTBOILED@"
	db "HI JUMP KICK@"
	db "GLARE@"
	db "$אוכל חלומות@"
	db "$גז רעיל@"
	db "BARRAGE@"
	db "LEECH LIFE@"
	db "LOVELY KISS@"
	db "$מתקפת שמיים@"
	db "TRANSFORM@"
	db "$בועה@"
	db "DIZZY PUNCH@"
	db "SPORE@"
	db "FLASH@"
	db "PSYWAVE@"
	db "$שכשוך@"
	db "ACID ARMOR@"
	db "CRABHAMMER@"
	db "EXPLOSION@"
	db "FURY SWIPES@"
	db "$בומרנג עצם@"
	db "$מנוחה@"
	db "ROCK SLIDE@"
	db "HYPER FANG@"
	db "SHARPEN@"
	db "CONVERSION@"
	db "$מתקפה משולשת@"
	db "SUPER FANG@"
	db "SLASH@"
	db "SUBSTITUTE@"
	db "$מאבק@"

